Change relative include paths to absolute include paths
woocommerce/action-scheduler pull request #604
Opened 2020-08-20 21:05 UTC by romarioraffington

Relates to woocommerce/woocommerce#27269 and woocommerce/woocommerce#27433

## Overview
Relative include paths in PHP can break, when server is running opcache. See here about vulnerability details.

WordPress.com deploy system refuses to include WooCommerce, because of that issue - for more context, see here - internal a8c discussion This PR changes the relative include paths to absolute include pathss.

2020-08-24 12:06 UTC, rrennick commented
> Not sure why the CI is throwing this error:

@romarioraffington Sometimes CI has hiccups that cause tests to fail. I triggered a rebuild of the failing run and it passed.

2020-09-02 12:21 UTC, artpi commented
Romario, there's one more file to change:

```
Error in: trunk/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:
Relative path includes are not allowed. Please fix this relative include before committing the file:
			include( "{$dir}{$class}.php" );

```
https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler.php#L122

I think we can pull `$dir` ahead of `"` and it'll be ok

2020-09-02 15:34 UTC, romarioraffington commented
> Romario, there's one more file to change:
> 
> ```
> Error in: trunk/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:
> Relative path includes are not allowed. Please fix this relative include before committing the file:
> 			include( "{$dir}{$class}.php" );
> ```
> 
> https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler.php#L122
> 
> I think we can pull `$dir` ahead of `"` and it'll be ok

Fixed in  9924e3b

2020-09-16 19:50 UTC, rrennick commented
@romarioraffington I updated this PR to be consistent with https://github.com/woocommerce/woocommerce/pull/27433.

2020-09-18 14:21 UTC, claudiosanches requested changes
There's no more a `$dir` variable, and also should be easier to just use `__DIR__` in those.

2020-09-18 14:21 UTC, claudiosanches commented on action-scheduler.php
> +		require_once( $dir . 'classes/ActionScheduler_Versions.php' );
```suggestion
		require_once( __DIR__ . '/classes/ActionScheduler_Versions.php' );
```

2020-09-18 14:21 UTC, claudiosanches commented on action-scheduler.php
> +		require_once( $dir . 'classes/abstracts/ActionScheduler.php' );
```suggestion
		require_once( __DIR__ . '/classes/abstracts/ActionScheduler.php' );
```

2020-09-18 14:27 UTC, claudiosanches approved these changes
All fixed now, but maybe we could revert the changes from `classes/abstracts/ActionScheduler.php`, since those doesn't change too much.

Thanks for your help!

2020-09-18 18:34 UTC, merged