Replace uses of `\ActionScheduler_Store::find_actions` with `\ActionScheduler_Store::query_actions`
woocommerce/action-scheduler pull request #752
Opened 2021-08-27 05:04 UTC by danielbitzer

The data store methods `\ActionScheduler_Store::find_actions` and `\ActionScheduler_Store::query_actions` essentially perform the same function and contain a lot of duplicate code. `find_actions` is less capable and makes a bunch of assumptions which are not implied in the name which makes `query_actions` a much better single choice to use moving forward.

This PR updates the `as_next_scheduled_action()` and `as_unschedule_action()` functions to use the preferred `query_actions` method.

Initially commented here: https://github.com/woocommerce/action-scheduler/pull/688#discussion_r696936795

The only risk I see here is that `find_action` has greater test coverage than `query_actions`. 

Note: `find_action` uses an INNER JOIN while `query_actions` uses as LEFT JOIN. This doesn't affect the end result AFAICS.

2021-09-02 01:23 UTC, danielbitzer commented
I definitely see where you're coming from. I agree that `find_actions` is a somewhat helpful shortcut method. Retrieving a single action definitely seems like a common use case in the plugin.

The main thing I don't like is that it does too much for a "typical data retrieval function" i.e. the extra logic to change the query ordering based on the `$param[status]` value. This should at least be stated in the doc block. Setting the default `status` to `pending` also seems a bit presumptuous for a query-type function but I guess it's a nice shortcut. I personally prefer functions that are more explicitly named like:
```php
store()->get_next_pending_action( $hook, $args, $group );

// and additionally
store()->get_last_complete_action( $hook, $args, $group );
store()->get_last_failed_action( $hook, $args, $group );
```

But agree that it's probably worth maintaining this method for library consumers even though they should be using the public function like `as_get_scheduled_actions()`.

2021-09-02 02:25 UTC, danielbitzer commented
I've updated this PR and I think I've addressed all your feedback. More feedback is welcome of course the discussion is still ongoing about the `find_action` method.

I ended up adding `query_action` as a really simple shortcut to retrieve a single action from the upgraded `::query_actions()` method. I believe this will be useful. Part of the reasoning is that I don't think we can safely upgrade `find_actions` to support multiple statuses because of its additional status handling logic.

2021-09-02 17:05 UTC, barryhughes commented
> The main thing I don't like is that it does too much for a "typical data retrieval function"

:100: 

> Part of the reasoning is that I don't think we can safely upgrade find_actions to support multiple statuses because of its additional status handling logic.

Good call.

> But agree that it's probably worth maintaining this method for library consumers even though they should be using the public function like as_get_scheduled_actions().

Yes, I'm just trying to be extra cautious here. Plus, depending on how you define library consumer, some may have custom store implementations of their own (and custom helper functions), rather than being 'simple end-consumers'. Certainly in general, though, the ideal is probably that they use the procedural API...but I don't know that we've actually publicized that recommendation any place.

2021-09-02 17:06 UTC, barryhughes requested changes
Nice—left a few more notes, but they are all very minor (linting) issues. Beyond that, LGTM!

2021-09-03 00:31 UTC, danielbitzer commented
Thanks @barryhughes! I fixed up those last few phpcs issues.

2021-09-03 01:53 UTC, barryhughes approved these changes
💥

2021-09-03 01:53 UTC, merged